name: "Tests"

# The workflow below runs when the release event triggers on Pull Requests and pushes to the main branch.
# For more information on the release event.
# See: [Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release)
# See: https://localheinz.com/articles/2022/01/24/creating-releases-with-github-actions/

on:
  push:
    branches:
      - main

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    name: "Tests for merge to main branch"
    if: github.ref == 'refs/heads/main'

    steps:
    
      # See: https://github.com/marketplace/actions/checkout
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - uses: ./.github/actions/ci
