name: "Update released versions"

# The workflow below runs when the release event triggers when tags are created.
# For more information on the release event.
# See: [Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#push)

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*'
      - 'v*'
      - 'latest'

jobs:
  release-linux:
    name: "Publish Linux packages"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64
        goos: [linux]
        goarch: ["386", amd64, arm64]

    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:

      # See: https://github.com/marketplace/actions/checkout
      - name: "Checkout repository"
        id: checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/publish-package
        with:
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          extension: ""
          tag: ${{ github.ref_name }}

  release-macos:
    name: "Publish macOS packages"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # build and publish in parallel: darwin/amd64, darwin/arm64
        goos: [darwin]
        goarch: [amd64, arm64]

    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
    
      # See: https://github.com/marketplace/actions/checkout
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - uses: ./.github/actions/publish-package
        with:
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          extension: ""
          tag: ${{ github.ref_name }}

  release-windows:
    name: "Publish Windows packages"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # build and publish in parallel: windows/386, windows/amd64
        goos: [windows]
        goarch: ["386", amd64]

    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
    
      # See: https://github.com/marketplace/actions/checkout
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - uses: ./.github/actions/publish-package
        with:
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          extension: ".exe"
          tag: ${{ github.ref_name }}
